Repository hanium2024/FE, pull requests merged in 2024-08, with the labels that each got.

#20 sprint5 feat: 건강일지 컴포넌트
  AppInner.tsx
  src/components/Comment.tsx
  src/components/DogCard.tsx
  src/components/ProfileCard.tsx
  src/pages/AddDogProfilePages/DogInfo.tsx
  src/pages/Camera.tsx
  src/pages/Health.tsx
  src/pages/Home.tsx
  src/pages/MissFoundPages/FoundPost.tsx
  src/pages/MissFoundPages/MissPost.tsx
Labels: enhancement

#24 sprint6 feat: 모든 기능 및 예외처리 작업 수행
  AppInner.tsx
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/assets/custom/Cafe24OhsquareAir-v2.0.ttf
  android/app/src/main/assets/custom/Inter_24pt-ExtraBoldItalic.ttf
  android/app/src/main/assets/fonts/Heanam.ttf
  android/app/src/main/assets/fonts/Inter_24pt-ExtraBoldItalic.ttf
  android/link-assets-manifest.json
  ios/MyPet.xcodeproj/project.pbxproj
  ios/MyPet/Info.plist
  ios/link-assets-manifest.json
  package-lock.json
  package.json
  src/api/fcmAlarmApi.ts
  src/assets/fonts/Heanam.ttf
  src/assets/fonts/Inter_24pt-ExtraBoldItalic.ttf
  src/components/Calendar.tsx
  src/components/Comment.tsx
  src/components/EachOrder.tsx
  src/components/InputFormat.tsx
  src/components/MissFound.tsx
  src/components/PickFormat.tsx
  src/components/Status.tsx
  src/components/WeeklyCalendar.tsx
  src/img/AppIcon.svg
  src/pages/AddDogProfilePages/DogInfo.tsx
  src/pages/AddDogProfilePages/DogProfileResult.tsx
  src/pages/Health.tsx
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/pages/MissFoundPages/Found.tsx
  src/pages/MissFoundPages/FoundDetail.tsx
  src/pages/MissFoundPages/FoundPost.tsx
  src/pages/MissFoundPages/Miss.tsx
  src/pages/MissFoundPages/MissDetail.tsx
  src/pages/MissFoundPages/MissFound.tsx
  src/pages/MissFoundPages/MissPost.tsx
  src/pages/MyInfo.tsx
  src/slices/order.ts
  src/slices/user.ts
  src/util.ts
  src/utils/dogBreeds.ts
  src/utils/getFCMToken.ts
  types/navigation.ts
  yarn.lock
Labels: enhancement

#26 Feautre/web3
  src/assets/json/HappyMaru.json
  src/pages/MyInfo.tsx
  src/services/web3Service.js
Labels: enhancement

#28 sprint6 fix: 타입수정
  src/components/Header.tsx
Labels: invalid

#29 sprint7: 인증서 모달 및 기타작업
  src/api/userApi.ts
  src/components/DateTimePick.tsx
  src/components/InputFormat.tsx
  src/components/InputImage.tsx
  src/components/PickFormat.tsx
  src/img/CloseIcon.svg
  src/pages/AddDogProfilePages/DogInfo.tsx
  src/pages/AddDogProfilePages/DogProfileResult.tsx
  src/pages/AddDogProfilePages/ProfileInfo.tsx
  src/pages/Home.tsx
  src/pages/MissFoundPages/FoundPost.tsx
  src/pages/MissFoundPages/FoundResultSuccess.tsx
  src/pages/MissFoundPages/MissPost.tsx
Labels: bug, enhancement, style

#30 sprint7 feat: 인증서 모달 완료
  src/img/CertificateImage.png
  src/img/CloseIcon.svg
  src/img/SafeMarkReverseIcon.svg
  src/pages/Home.tsx
  src/pages/MissFoundPages/FoundResultSuccess.tsx
  src/pages/MyInfo.tsx
  src/services/web3Service.js
Labels: enhancement

#31 sprint7 feat: 데모영상 촬영용 작업
  src/components/DogCard.tsx
  src/components/FoundCard.tsx
  src/components/MissCard.tsx
  src/components/ProfileCard.tsx
  src/pages/AddDogProfilePages/DogProfileResult.tsx
  src/pages/Home.tsx
  src/pages/MissFoundPages/Found.tsx
  src/pages/MissFoundPages/FoundDetail.tsx
  src/pages/MissFoundPages/Miss.tsx
  src/pages/MissFoundPages/MissDetail.tsx
  src/pages/MissFoundPages/MissFound.tsx
  src/pages/MyInfo.tsx
  src/services/web3Service.js
Labels: enhancement, fix, style

#32 release: v0.1.0
  AppInner.tsx
  src/pages/AddDogProfilePages/DogProfileResult.tsx
  src/pages/MissFoundPages/Found.tsx
  src/pages/MissFoundPages/Miss.tsx
  src/services/web3Service.js
Labels: bug

#33 sprint7 fix: console제거
  package-lock.json
  package.json
  src/hooks/usePermissions.ts
  src/hooks/useSocket.ts
  src/modules/TMap.ts
  src/pages/AddDogProfilePages/DogNoseCamera.tsx
  src/pages/AddDogProfilePages/DogProfileResult.tsx
  src/pages/Complete.tsx
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/pages/MyInfo.tsx
  src/utils/convertType.ts
  yarn.lock
Labels: fix
